language: node_js
node_js:
- '16.20.2'
env:
  global:
  - MATTERMOST_CHANNEL=publication
  # REGISTRY_TOKEN(editor=cozy, app=ovh)
  - secure: cBG9QNv1Qzc8mZSfoAYRAGwM/f6rJJpbTjEmCV7q6x6fCG6ANjyd6MNqfpeC2iuT/ZYeCo648Pd/vioba8fLTm5h8Q61pQJD6iW40WjpKDq+V8wYq2t7SYqGxIy82a1eVcqQVzvpf8Ld/1dNG76yUyHCW5ep7alwJlWItkg+vY6zNYQlDNWdzhw1XtZrhdIPQ5xhIay6/y6tr3YJ8nA4NnCpBMjOfUppEmAoye69tvaDEqaJEbRd9l+dt2cAxVdMK6QpKgqG20lKd9QwmqwsAX+h3yN+H3mEA//aos8PBdnAloXywO+i8KE9CL+UszUFKdjxuaq936e13iS+jBXsx+UQ8VbuIy2N4KlHey4X2n5ifcv/qVS6d4v7FG5Jui0Tk+YOSeroqsn2Ld2Us5rByV+e07101IwAwISfRlyEYvrSm89rR5XGfxnKJ8SXITcxeFq9TtP7rBdcdm2EQYtzMrT940Sm1h6eroHED0k9biZKMknp8Tq4the6kiTSnCW7e8mk7Fm6iuq8XZ39W+vxdlwi8AOmza/D3K+BkL2/pWbvlbjWnzKinKS+6s7O6yufU1OmOrVYwwFpY1DE7GnHU1tX+lUGFZqdoZ2ba2PoRevEFPY+s6SCheLPdbvOZ/lFYgbEpnfiGSoPYNvKiXqdiPUv02/RiezXDVEGYaH0zIk=
  # MATTERMOST_HOOK_URL
  - secure: PO7AR7/tM4h3rNF29KbBSEHALJKRMUsJ8XjIVovrCaZurvnNxBY4ijJ2MrbjkKsiENavTWVeJxx6WcP2zGMa4EFA0LozLXWs6/BfCxg+fLZyWmAk9Tyy/JNNLh9V3oNo4B83yhxORMQGfV3U1iSpdJAbNI4junR2QpT5DRa3EyqGrkMR9eZED7ERvmM/QYlrYIa2NeN4T4x9TkU7+VeZaiY7ReE1wPl0tR6dAq4s2ker7Y87Jly2TraJRhD1m1Acxh8nlaK4+glocJ1eLMKIoefmwiS7U3PgR/F5CAT5h3ezsSNL42jb5hkC1bLS7pmXmAVZyU/esD5mQyBczJVcnurJNdweOQRBk0QaGoL18uMa36/0UDQ11OPfVS7SkFgMDs3jmpveOvVEB7eY+MBOmu7hRtyXbEQaP7rtdKAUdtHrpQ4IUodFq+2BMjQCY0gWbwtFEtohuO0dYgpNr6rm78+HgiLWdJxcFyReWhWhoeSJ/3qPZ+hPFDAWx6P80wqWMzMVaRP4TmGAIPx0HKXoYRBMOWZuMh68MRjXN5ci+OCI12VCD1Sen+SrvVQzKOTdk4l0dSHvTZYneQc+k5w+hscJCB9yhilN737cEv7sRgwoSDGoDdPo013pEa8mCPqBKrdi1uXAtZEdEMftJR+3BTfnv8615UTB4pAgD3dsgN4=
cache:
  yarn: true
  directories:
  - node_modules
branches:
  except:
  - build
  - build-debug
script:
- yarn lint
- yarn build
deploy:
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish
  on:
    branch: master
- provider: script
  skip-cleanup: true
  script: DEPLOY_BRANCH=build yarn deploy && yarn cozyPublish --postpublish mattermost
  on:
    tags: true
before_install:
- openssl aes-256-cbc -K $encrypted_8ebb1ef83f64_key -iv $encrypted_8ebb1ef83f64_iv
  -in github_deploy_key.enc -out /tmp/github_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/github_deploy_key
- ssh-add /tmp/github_deploy_key
after_deploy:
- rm /tmp/github_deploy_key
- ssh-add -D
